export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  BERTH_PLAN_NOT_FOUND: "BERTH_PLAN_NOT_FOUND",
  BERTH_NOT_FOUND: "BERTH_NOT_FOUND",
  BERTH_LENGTH_UNSUITABLE: "BERTH_LENGTH_UNSUITABLE",
  BERTH_REASSIGN_FAILED: "BERTH_REASSIGN_FAILED"
} as const;
