export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  PLAN_NOT_FOUND: "PLAN_NOT_FOUND",
  BERTH_NOT_FOUND: "BERTH_NOT_FOUND",
  BERTH_TOO_SHORT: "BERTH_TOO_SHORT",
  REASSIGN_STILL_CONFLICT: "REASSIGN_STILL_CONFLICT"
} as const;
